module.exports = {
  purge: {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx, mdx}"],
    safelist: [
      "hljs ",
      "hljs-doctag",
      "hljs-keyword",
      "hljs-meta",
      "hljs-template-tag",
      "hljs-template-variable",
      "hljs-type",
      "hljs-variable",
      "hljs-title",
      "hljs-attr",
      "hljs-attribute",
      "hljs-literal",
      "hljs-meta",
      "hljs-number",
      "hljs-operator",
      "hljs-variable",
      "hljs-selector-attr",
      "hljs-selector-class",
      "hljs-selector-id",
      "hljs-regexp",
      "hljs-string",
      "hljs-built_in",
      "hljs-symbol",
      "hljs-comment",
      "hljs-code",
      "hljs-formula",
      "hljs-name",
      "hljs-quote",
      "hljs-selector-tag",
      "hljs-selector-pseudo",
      "hljs-subst",
      "hljs-section",
      "hljs-bullet",
      "hljs-emphasis",
      "hljs-strong",
      "hljs-addition",
      "hljs-deletion",
      "hljs-char",
      "hljs-link",
      "hljs-params",
      "hljs-property",
      "hljs-punctuation",
      "hljs-tag",
      "",
    ],
    options: {
      keyframes: true,
    },
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    flex: {
      "almost-half": "0 0 42%",
      half: "0 0 50%",
    },
    extend: {
      typography: (theme) => ({
        DEFAULT: {
          css: {
            img: {
              marginTop: 0,
              marginBottom: 0,
            },
            a: {
              color: "rgb(37,99,235)",
              textDecoration: "none",
              borderRadius: ".25rem",
              wordBreak: "break-all",
              "&:hover": {
                backgroundColor: "rgb(219,234,254)",
              },
            },
          },
        },
      }),
    },
    fontFamily: {
      sans: [
        "pt-sans",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
    },
  },
  variants: {
    extend: {},
  },
  plugins: [require("@tailwindcss/typography")],
};
